# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Import Game Files
        env:
          IMPORT_URL: ${{ secrets.IMPORT_URL }}
        run: |
          mkdir -p download
          wget "$IMPORT_URL"
          tar -xzf dredmor.tar -C download
          cp -r download/* ./
          rm dredmor.tar
          rm -rf download
      - name: XML Fixes
        continue-on-error: true
        run: |
          sed -i 's|"items/component_parts_iron|"\.\./data/items/component_parts_iron|g' ./expansion2/game/itemDB.xml
          sed -i 's|"sprites/fhero/hero_run_d|"\.\./data/sprites/fhero/hero_run_d|g' ./expansion2/game/monDB.xml
          sed -i 's|"sprites/hero/hero_run_d|"\.\./data/sprites/hero/hero_run_d|g' ./expansion2/game/monDB.xml
          sed -i 's|"sprites/monster/canisterA/canisterA.xml|"sprites/monster/canisterA/canisterA0000.png|g' ./expansion2/game/monDB.xml
          sed -i 's|"sprites/monster/raven/raven_fly_d.xml|"sprites/monster/raven/raven_fly_d_000.png|g' ./expansion2/game/monDB.xml
          sed -i 's|"sprites/monster/raven/raven_fly_d.xml|"\.\./data/sprites/monster/raven/raven_fly_d_000.png|g' ./expansion3/game/monDB.xml
          sed -i 's|"sprites/monster/robo/Robo_Walk_Down|"sprites/monster/Robo/Robo_Walk_Down|g' ./data/game/monDB.xml

          sed -i 's|</itemDB>|<item name="Lockpick" iconFile="items/lockpick\.png" ><price amount="10"/></item></itemDB>|g' ./data/game/itemDB.xml
          sed -i 's|"lockpick"|"Lockpick"|g' ./data/game/skillDB.xml
          sed -i 's|"lockpick"|"Lockpick"|g' ./expansion/game/skillDB.xml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Delete Artifacts
        uses: joutvhu/delete-artifact@v2.0.1
